kind: pipeline
type: docker
name: PocketBook
 
trigger:
  event:
    - push

#steps:
  #- name: build
    #image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dotnet7-maui:latest
    #commands:
      #- cd Sources/
      #- dotnet restore PocketBook.sln
      #- dotnet build PocketBook.sln -c Release --no-restore /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT -property:Aapt2ToolPath=$ANDROID_SDK_ROOT/build-tools/33.0.0

  #- name: code-analysis
    #image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dronesonarplugin-dotnet7-maui
    #secrets: [ SECRET_SONAR_LOGIN ]
    #environment:
      #sonar_host: https://codefirst.iut.uca.fr/sonar/
      #sonar_token:
        #from_secret: SECRET_SONAR_LOGIN
    #commands:
      #- cd Sources/
      #- dotnet restore PocketBook.sln
      #- dotnet sonarscanner begin /k:$${project_key} /d:sonar.host.url=$${sonar_host} /d:sonar.coverageReportPaths="coveragereport/SonarQube.xml" /d:sonar.coverage.exclusions=$${coverage_exclusions} /d:sonar.login=$${sonar_token} 
      #- dotnet build PocketBook.sln -c Release --no-restore /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT -property:Aapt2ToolPath=$ANDROID_SDK_ROOT/build-tools/33.0.0
      #- dotnet test PocketBook.sln --logger trx --no-restore /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT -property:Aapt2ToolPath=$ANDROID_SDK_ROOT/build-tools/33.0.0 /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect "XPlat Code Coverage"
      #- reportgenerator -reports:"**/coverage.cobertura.xml" -reporttypes:SonarQube -targetdir:"coveragereport"
      #- dotnet publish MauiApp/MauiApp.csproj -c Release --no-restore -o $CI_PROJECT_DIR/build/release -f:net7.0-android /p:AndroidSdkDirectory=/usr/lib/android-sdk
      #- dotnet sonarscanner end /d:sonar.login=$${sonar_token}