kind: pipeline
type: docker
name: PocketBook
 
trigger:
  event:
    - push

steps:
  - name: build
    image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dotnet7-maui:latest
    commands:
      - cd Sources/
      - dotnet restore PocketBook.sln
      - dotnet build PocketBook.sln -c Release --no-restore /p:AndroidSdkDirectory=$ANDROID_SDK_ROOT -property:Aapt2ToolPath=$ANDROID_SDK_ROOT/build-tools/33.0.0