kind: pipeline
type: docker
name: PocketBook
 
trigger:
  event:
    - push

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - name: docs
        path: /docs
    commands:
      - cd Sources/
      - dotnet restore PocketBook.sln
      - dotnet build PocketBook.sln -c Release --no-restore
      - dotnet publish PocketBook.sln -c Release --no-restore -o CI_PROJECT_DIR/build/release